project: 
  type: website
  output-dir: docs
  
website:
  title: "Initiation à la Statistique Textuelle"
  
  navbar:
    type: inverse
    left:
      - text: "Supports"
        menu:
        - text: "Présentation générale"
          href: Intro.qmd
        - text: "Pas-à-pas"
          href : QO_Pee_K1.qmd
      - text: "Exercices"
        href: Exercices_enonces.html
        
      - text: "Ressources"
        href: biblio.html
    right:
      - icon: github
        href: https://github.com/benegarbi/AtelierQO_R
format:
  html: 
    theme: cosmo
    toc: true
    toc-depth: 3